/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yellowcab;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CollectionType implements org.apache.thrift.TEnum {
  /**
   * ordered Collection
   */
  DATA_FEED(0),
  /**
   * unordered Collection
   */
  DATA_SET(1);

  private final int value;

  private CollectionType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CollectionType findByValue(int value) { 
    switch (value) {
      case 0:
        return DATA_FEED;
      case 1:
        return DATA_SET;
      default:
        return null;
    }
  }
}
