/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yellowcab;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * Represents known service types
 * 
 */
public enum ServiceType implements org.apache.thrift.TEnum {
  COLLECTION_MANAGEMENT(0),
  DISCOVERY(1),
  INBOX(2),
  POLL(3);

  private final int value;

  private ServiceType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ServiceType findByValue(int value) { 
    switch (value) {
      case 0:
        return COLLECTION_MANAGEMENT;
      case 1:
        return DISCOVERY;
      case 2:
        return INBOX;
      case 3:
        return POLL;
      default:
        return null;
    }
  }
}
